#include "app.hpp"
#include <cmath>
#include <map>
#include <set>
#include <regex>
#include "si/mapping_policy.hpp"
#include "si/direction_policy.hpp"
#include "window_ui.cpp"
#include "window_workspace.cpp"
#include "window_mapping.cpp"
#include "window_analysis.cpp"
#include "window_results.cpp"
#include "window_plot_controller.cpp"
#include "window_project.cpp"
#include "window_export.cpp"
#include "window_validation.cpp"
